-- file auto generated by Grit Editor, be careful when modifying this manually
-- this file stores all editor configurations.

editor_cfg = {
  default_game_mode = "First Person",
  directory         = "./editor",
  load_startup_map  = false,
  maps_dir          = "../maps",
  mode_selected     = "translate",
  startup_map       = "/editor/default_config/default_map/defaultmap.gmap",
  step_size         = 0.1,
  thumbnails_size   = vector2(256, 256),
}